trigger:
- '*'

variables:
  buildConfiguration: 'Release'
  webRepository: 'web'
  imageName: 'devopsusecase3'
  tag: '$(Build.BuildId)'
  RegistryName: 'tailspinspacegamemcg.azurecr.io'

stages:
- task: AzureCLI@2
  displayName: 'Login to ACR using Managed Identity'
  inputs:
    azureSubscription: 'Resource Manager - Tailspin - Space Game'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      set -e
      az acr login --name tailspinspacegamemcg

- task: Docker@2
  displayName: 'Build and push the image to container registry'
  inputs:
    command: buildAndPush
    buildContext: $(Build.Repository.LocalPath)
    # Fully qualified repo so docker push goes to ACR, not Docker Hub
    repository: tailspinspacegamemcg.azurecr.io/$(webRepository)
    dockerfile: '$(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/DockerFile'
    tags: |
      $(tag)
  # If Buildx isn't installed yet, disable BuildKit to avoid errors
  env:
    DOCKER_BUILDKIT: '0'

- stage: 'Deploy'
  displayName: 'Deploy the container'
  dependsOn: Build
  jobs:
  - job: 'Deploy'
    displayName: 'Deploy job'
    pool:
      vmImage: 'ubuntu-22.04'
    variables:
    - group: Release
    steps:
    - task: AzureWebAppContainer@1
      inputs:
       appName: $(WebAppNameStaging)
       azureSubscription: 'Resource Manager - Tailspin - Space Game'
       imageName: $(RegistryName)/$(webRepository):$(build.buildId)