trigger:
- '*'

variables:
  buildConfiguration: 'Release'
  webRepository: 'web'
  imageName: 'devopsusecase3'
  tag: '$(Build.BuildId)'
  RegistryName: 'tailspinspacegamemcg.azurecr.io'

stages:
- stage: Build
  displayName: 'Build and push'
  jobs:
  - job: Build
    displayName: 'Build job'
    pool:
      name: 'VM Pool' 
    steps:
    - task: DockerInstaller@0
      inputs:
        dockerVersion: '27.0.2'

    - task: Docker@2
      displayName: 'Build and push the image to container registry'
      inputs:
        command: buildAndPush
        containerRegistry: 'ACR New'  # your Docker Registry (ACR) service connection (Managed Identity)
        repository: $(webRepository)   # e.g., myregistry.azurecr.io/app or just app
        buildContext: '$(Build.SourcesDirectory)/Tailspin.SpaceGame.Web'
        dockerfile: '$(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/Dockerfile'
        tags: |
          $(tag)

- stage: 'Deploy'
  displayName: 'Deploy the container'
  dependsOn: Build
  jobs:
  - job: 'Deploy'
    displayName: 'Deploy job'
    pool:
      vmImage: 'ubuntu-22.04'
    variables:
    - group: Release
    steps:
    - task: AzureWebAppContainer@1
      inputs:
       appName: $(WebAppNameStaging)
       azureSubscription: 'Resource Manager - Tailspin - Space Game'
       imageName: $(RegistryName)/$(webRepository):$(build.buildId)